stages:
  - init
  - build
  - staging
  - deploy

cache:
  paths:
    - node_modules/

init:
  stage: init
  script:
    - npm install
  only:
    - dev

build_dev:
  stage: build
  before_script:
    - export REACT_APP_HOST=$HOST_DEV
    - export REACT_APP_HOST_API=$HOST_DEV
    - export REACT_APP_HOST_LOGIN=$HOST_DEV_LOGIN
  script: 
    - npm run build
    - cp -f ~/project/wait/wait .
    - docker build -t $DOCKER_REPOSITORY/dev-apps/itpm-ui .
  only:
    - dev

staging_dev:
  stage: staging
  script:
    - docker push $DOCKER_REPOSITORY/dev-apps/itpm-ui
    - docker rmi $DOCKER_REPOSITORY/dev-apps/itpm-ui
  only:
    - dev
